### ISSUE TITLE
Prefer single quotes over double quotes

### ISSUE THREAD

**Issue by carsonfarmer** [Interactions-as-a-Service/d1-orm#60]
**Describe the bug**
When specifying a string defaultValue for a given model, the value is "encoded" with double quotes in the create statement. While this is technically ok with SQLite, it is actually not best practice (https://www.sqlite.org/quirks.html). While I understand that this is not a high-priority issue, it is causing downstream issues for me when use this for local development, so I thought I would submit an issue in case it is hitting anyone else. I'm happy to submit a PR for this (tiny) fix, if that would be accepted.

The following section of a model:
```javascript
...
name: {
  type: DataTypes.STRING,
  notNull: true,
  defaultValue: "John Doe",
},
...
```

runs into this on line 138 of current main:

```javascript
defaultStr = `"${column.defaultValue}"`;
```

**Expected behavior**

That line should probably be

```javascript
defaultStr = `'${column.defaultValue}'`;
```

**Comment by Skye-31** [comment]
Hi @carsonfarmer.

Thanks for the issue! This should be resolved in v0.7.2.
